name: Test CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check environment variables
        run: env

      - name: Install Allure CLI
        uses: allure-framework/allure-action@v2

      - name: Build & Test
        run: mvn clean test

      - name: Generate Allure Reports
        run: allure generate allure-results --clean -o target/allure-report

      - name: Upload Allure reports
        uses: actions/upload-artifacts@v3
        with:
          name: allure-reports
          path: target/allure-report
          
          
          



