name: Security CI

on:
  push:
    branches:
      - '**'

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache OWASP Dependency-Check data
        uses: actions/cache@v3
        with:
          path: ~/.dependency-check
          key: dependency-check-cache

      - name: Run Dependency Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn org.owasp:dependency-check-maven:check \
              -Dnvd.apiKey=$NVD_API_KEY \
              -Ddata.directory=$HOME/.dependency-check \
              -Dformat=ALL \
              -DfailBuildOnCVSS=11

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile

      - name: Build Docker image
        run: docker build -t petlibrary:ci -f docker/Dockerfile .
